### ISSUE TITLE
Test file fails with 'AttributeError: no attribute "boundingRect"'

### ISSUE THREAD

**Issue by Veldrovive** [jmitrevs/matplotlib_backend_qtquick#1]
I am getting two error actually.

The first is that `app = QtGui.QGuiApplication()` wants a parameter. I know for other sources that this is usually `sys.argv` so I just added that in for a test.

The second error I get is the one in the title, namely `AttributeError: 'FigureCanvasQtQuickAgg' object has no attribute 'boundingRect'` from `backend_qtquick.py` on line 87. I'm assuming that it is supposed to inherit `boundingRect` from `QtQuick.QQuickPaintedItem` but it seems to me that those don't have a `boundingRect` attribute.

Do I have versions wrong?
I installed PyQt through the PyQt5 PyPi repository which gives a Qt version of 5.14.2.
My Matplotlib version is 3.2.1 as in your Readme.
My Python version is 3.7.

**Comment by jmitrevs** [comment]
Thanks for the opening the issue. I will look into it tomorrow. I only tested with PySide2, but will try it with PyQt5.

**Comment by Veldrovive** [comment]
Ah, I didn't realize there would be a difference between the two implementations.
However, running with PySide2 makes it work flawlessly even through the Qt versions are the same.

I would appreciate it if you would take a look and see if there is an easy way to port your implementation to work with PyQt5 as well but, in any case, great work on this. It seems very well done.

**Comment by jmitrevs** [comment]
I believe I have fixed these problems in 0.0.6.
