### ISSUE TITLE
Request for a more feature filled example

### ISSUE THREAD

**Issue by Veldrovive** [jmitrevs/matplotlib_backend_qtquick#2]
First off, is the test supposed to render an interactive graph with a toolbar? I see that the `DisplayBridge` class creates a `NavigationToolbar2QtQuick` and passes the Canvas, but there is no toolbar in the scene. I also see that when you implement `_init_toolbar`, you say to build widgets in QML. How is that done?

The test example is good to see how to render a graph but without a more thorough example or complete documentation, it is difficult to see how many aspects are intended to work.

I see that this is a very new repository so it may be inefficient to write up full documentation now so an example that makes use of many features would be helpful.

**Comment by jmitrevs** [comment]
Hi,

The test just closes 5 seconds after opening.  I didn’t add interactions, though in the application I wrote using it, I do have interactions. I will try to add documentation. I am neither a Qt not matplotlib expert; this just came out of me trying to get my application working. 

Jovan

**Comment by jmitrevs** [comment]
For the moment, I added a bit more to the README, cutting and pasting from some code I wrote. I will try to put an actual example this weekend.

The test is meant to be noninteractive so you can run it from the command line and have it pass or fail. I will make the example interactive.

**Comment by jmitrevs** [comment]
I just uploaded an example with interactions in the examples directory in the repository.

**Comment by Veldrovive** [comment]
Awesome.

Thank you for doing this. It will make my life so much easier.
