### ISSUE TITLE
Why are Qt classes being imported from qt_compat instead of PyQt or PySide2 themselves?

### ISSUE THREAD

**Issue by Mr-Crabman** [jmitrevs/matplotlib_backend_qtquick#4]
Hi, I've been taking a look at this library because I need to draw a static (ie doesn't dynamically change) audio waveform in QML akin to the ones Audacity or SoundCloud would have.

However, something about the example is confusing me; you seem to be importing QtGui, QtQml, and QtCore from matplotlib_backend_qtquick.qt_compat, rather than Qt (in my case, PySide2).

I don't quite understand what this does clearly; to use this in my project, do I have to import from qt_compat instead of PySide2? If I have multiple other python files where I import PySide2 classes (such as QObject so that I can subclass a QObject), do I have to use your import here too (ie throughout the whole project)?  And do I need to have PySide2 myself as well or is it already included in your project?

Oh, and also, would you say this library is performant for very large plots? I will need to be having a waveform potentially hundreds of thousands of pixels wide (though obviously I will be putting this in a ScrollView with clipping), and worry about QML's ability to hold such a large image, particularly if it's not just an image, but some form of canvas (which I assume FigureCanvas is).

Apologies if this isn't quite a proper "issue"; I would have PM'd instead because I'm not sure, but GitHub doesn't have a function like that.

**Comment by jmitrevs** [comment]
For the importing, I tried to follow what matplotlib does. Some of it is to be compatible with both PySide2 and PyQt5. The qt_compat layer makes it possible to use either of those packages. For your project, though, you can import directly from PySide2 or PyQt5. You need to install one of those packages, though. You also need matplotlib.

I really don't know about the performance. The examples show generally how I use the package, and for what I do, it performs fine.

**Comment by Mr-Crabman** [comment]
Thank you very much; so to cement in my head, I have matplotlib and PySide2, I don't need to import the Qt stuff through qt_compat? And I assume I import from backend_qtquick and backend_qtquickagg rather than matplotlib directly?

**Comment by jmitrevs** [comment]
You can import them directly.
